FROM nvcr.io/nvidia/tensorflow:18.12-py3

RUN pip3 install scikit-image 'keras==2.1.6' && \
    apt-get update && apt-get install -y libsm6 libxext6 libxrender-dev && \
    pip3 install opencv-python imgaug